# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: 'migrations/.*\.py|Procfile|[aw]sgi\.py|node_modules|.git|\.polar'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key
      - id: mixed-line-ending
        args: [--fix, lf]
  # - repo: https://github.com/pre-commit/mirrors-eslint
  #   rev: 'v8.20.0'
  #   hooks:
  #     - id: eslint
  #       files: \.[jt]sx?$
  #       types: [file]
  #       additional_dependencies:
  #         - '@eslint/js'
  #         - 'eslint'
  #         - 'eslint-plugin-react'
  #         - 'eslint-plugin-unused-imports'
  #         - 'globals'
  #       args:
  #         - '--fix'
  #         - '--quiet'
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v2.7.1'
    hooks:
      - id: prettier
        language_version: 16.0.0
        additional_dependencies:
          - prettier
          - '@trivago/prettier-plugin-sort-imports@^3.2.0'
  - repo: local
    hooks:
      - id: tofu-fmt
        name: tofu format
        description: Format .tf files
        entry: tofu fmt
        language: system
        files: .tf$
